### ISSUE TITLE
Filtro por contenido de rutina

### ISSUE THREAD

**Issue by jrsg** [UniversidadCristobalColon/integrador-ago-dic-2018#25]
¿Qué te parece si en la tabla http://35.225.5.28/admin/catalogos/rutinas/ donde se listan todas las rutinas, quitas la columna "Actualizada" y agregas la descripción de la rutina? Esto para que el usuario pueda filtrar por algún movimiento en particular, ejemplo "push-ups" y filtre las rutinas que contienen push-ups.

Lo anterior es una sugerencia / prueba que a lo mejor resulte muy útil.

**Comment by JudyFararoni** [comment]
no es factible, sorry
