### ISSUE TITLE
Ajusta la ruta del archivo eventoClases.php

### ISSUE THREAD

**Issue by jrsg** [UniversidadCristobalColon/integrador-ago-dic-2018#79]
https://github.com/UniversidadCristobalColon/integrador-ago-dic-2018/blob/34eff2aeb901e0ecbe01f3a9c7a14a93e1f9e253/user/clases/index.php#L75

Elimina la ruta `http://localhost:8888/int2018/user/clases/`, sólo deja `eventoClases.php`. Esto aplica para los dos calendarios (admin y user)

**Comment by dimetremendo** [comment]
Ya quedo profe

**Comment by jrsg** [comment]
Pues sube el pull-request con el cambio

**Comment by dimetremendo** [comment]
🤙🏼
